server:
  port: 8000
spring:
  application:
    name: allin-monitor
  profiles:
    active: dev
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS