spring:
  profiles:
    active: dev
zuul:
  prefix: /api
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: allin-consumer  # 转发到消费者 /ribbon/
    feign:
      path: /feign/**
      serviceId: allin-consumer  # 转发到消费者 /feign/
  ribbonIsolationStrategy: THREAD
    threadPool:
      useSeparateThreadPools: true
      threadPoolKeyPrefix: zuulgateway
    max:
      host:
        max-per-route-connections: 200
        max-total-connections: 500
    host:
      socket-timeout-millis: 5000
      connect-timeout-millis: 10000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 3000 #请求处理的超时时间
  ConnectTimeout: 3000 #请求连接的超时时间
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  OkToRetryOnAllOperations: true #对所有请求都进行重试

hystrix:
  threadpool:
    default:
      coreSize: 20 #并发执行的最大线程数，默认10
      maximumSize: 50
      maxQueueSize: -1 #BlockingQueue的最大队列数
      allowMaximumSizeToDivergeFromCoreSize: true
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            interruptOnTimeout: false
            timeoutInMilliseconds: 36000 #(ReadTimeout+ConnectTimeout)*(MaxAutoRetries+1)*(MaxAutoRetriesNextServer+1)

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  hystrix:
    enabled: true