eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
#spring:
#  boot:
#    admin:
#      client:
#        url: "http://localhost:8000"
#        instance:
#          instance.service-base-url: ${spring.application.name}
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        serviceName: allin-consumer	# 注册到consul的服务名称
#    config:
#      discovery:
#        enabled: true  # 开启服务发现
#        serviceId: allin-config # 配置中心服务名称
#      name: ${spring.application.name}  # 对应{application}部分
#      profile: dev  # 对应{profile}部分
#      label: master  # 对应git的分支，如果配置中心使用的是本地存储，则该参数无用
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: username
#    password: password
#  zipkin:
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
#feign熔断器开关
feign:
  hystrix:
    enabled: false
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

