server:
  port: 8020
spring:
  profiles:
    active: dev
  application:
    name: allin-config
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/shiyuan2he/allin.git  # 配置git仓库的地址
          search-paths: allin-server/config-repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: shiyuan2he  # git仓库的账号
          password: heshiyuan98  # git仓库的密码
          force-pull: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: username
#    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"
